refining github actions

diff --git a/.github/workflows/download_json.yml b/.github/workflows/download_json.yml
--- a/.github/workflows/download_json.yml
+++ b/.github/workflows/download_json.yml
@@ -19,19 +19,15 @@ jobs:
         with:
           node-version: 24
 
-      - name: Run download_json.mjs
-        run: node download_json.mjs
+      - name: Run download_json.js
+        run: node download_json.js
 
-
-      # we need to run build after this of refine to push to remote as well
+      # [skip cli] - will not tigger CI pipelin
+      # echo "..." prevents fail on no changes to commit
       - name: Commit and push changes
         run: |
-          git config --global user.name "github-actions[bot]"
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-
+          git config --global user.name "github-actions-bot"
+          git config --global user.email "github-actions-bot@users.noreply.github.com"
           git add _public-vite/
-
-          # The '|| echo' ensures the workflow doesn't fail if the data is identical.  Consider to remove
-          git commit -m "Automated update of _public-vite [skip ci]" || echo "No changes to commit"
-
+          git commit -m "github actions update [skip ci]" || echo "No changes to commit"
           git push origin main
